## Imports

Packages

In [1]:
import numpy as np
import scipy as sp
import pandas as pd
import matplotlib.pyplot as plt

Data

In [4]:
df = pd.read_csv('Ionosphere Data _ Final Exam.csv')
df = df.iloc[:,0:5]

,Altitude [km],Electron Density [m-3],dAlt [m],dNe [m-3],TEC (Area Under Curve)
0,100,2.270000e+10,0,0.000000e+00,0.000000e+00
1,150,2.800000e+10,50000,2.540000e+10,1.270000e+15
2,200,5.040000e+10,50000,3.920000e+10,1.960000e+15
3,250,1.400000e+11,50000,9.520000e+10,4.760000e+15
4,300,2.190000e+11,50000,1.800000e+11,8.980000e+15
5,350,2.010000e+11,50000,2.100000e+11,1.050000e+16
6,400,1.520000e+11,50000,1.770000e+11,8.830000e+15
7,450,1.080000e+11,50000,1.300000e+11,6.500000e+15
8,500,7.600000e+10,50000,9.200000e+10,4.600000e+15
9,550,5.450000e+10,50000,6.530000e+10,3.260000e+15
10,600,4.010000e+10,50000,4.730000e+10,2.370000e+15
11,650,3.040000e+10,50000,3.530000e+10,1.760000e+15
12,700,2.360000e+10,50000,2.700000e+10,1.350000e+15
13,750,1.870000e+10,50000,2.120000e+10,1.060000e+15
14,800,1.520000e+10,50000,1.700000e+10,8.480000e+14
15,850,1.250000e+10,50000,1.390000e+10,6.930000e+14
16,900,1.050000e+10,50000,1.150000e+10,5.750000e+14
17,950,8.960000e+09,50000,9.730000e+09,4.870000e+14
18,1000,7.720000e+09,50000,8.340000e+09,4.170000e+14
19,1050,6.730000e+09,50000,7.230000e+09,3.610000e+14
20,1100,5.920000e+09,50000,6.330000e+09,3.160000e+14
21,1150,5.260000e+09,50000,5.590000e+09,2.800000e+14
22,1200,4.710000e+09,50000,4.990000e+09,2.490000e+14
23,1250,4.240000e+09,50000,4.480000e+09,2.240000e+14
24,1300,3.850000e+09,50000,4.050000e+09,2.020000e+14
25,1350,3.510000e+09,50000,3.680000e+09,1.840000e+14
26,1400,3.220000e+09,50000,3.370000e+09,1.680000e+14
27,1450,2.970000e+09,50000,3.100000e+09,1.550000e+14
28,1500,2.750000e+09,50000,2.860000e+09,1.430000e+14
29,1550,2.550000e+09,50000,2.650000e+09,1.330000e+14
30,1600,2.380000e+09,50000,2.470000e+09,1.230000e+14
31,1650,2.230000e+09,50000,2.310000e+09,1.150000e+14
32,1700,2.090000e+09,50000,2.160000e+09,1.080000e+14
33,1750,1.970000e+09,50000,2.030000e+09,1.020000e+14
34,1800,1.860000e+09,50000,1.920000e+09,9.580000e+13
35,1850,1.760000e+09,50000,1.810000e+09,9.050000e+13
36,1900,1.670000e+09,50000,1.720000e+09,8.580000e+13
37,1950,1.590000e+09,50000,1.630000e+09,8.150000e+13
38,2000,1.510000e+09,50000,1.550000e+09,7.750000e+13

## Params

In [3]:
print("hi")

hi